<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MVCAllOptions.Orders</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Mapperly" Version="10.1.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.1.0" />
    <ProjectReference Include="..\MVCAllOptions.Orders.Application.Contracts\MVCAllOptions.Orders.Application.Contracts.csproj" />
    <ProjectReference Include="..\MVCAllOptions.Orders.Domain\MVCAllOptions.Orders.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\MVCAllOptions.Application.Contracts\MVCAllOptions.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
